logging:
  level:
    org.springframework.security: DEBUG
security:
  user:
    password: password
  sessions: ALWAYS
zuul:
  routes:
    ui:
      url: http://localhost:8081
    admin:
      url: http://localhost:8082
    resource:
      url: http://localhost:9000
spring:
  redis:
    host: localhost
    port: 6379
